#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  
  block compile bundler install --no-deployment
  block compile bundler update "$@"
}

main "$@"
