#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_travis="0.0.1"
  jq -n --arg travis "$ver_travis" '{travis: $travis}'
}

version "$@"
