#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_travis="$(travis --version 2>/dev/null || true)"
  jq -n --arg travis "$ver_travis" '{travis: $travis}'
}

version "$@"
